In [2]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap2.transforms import rot_y

print("Passive y axis rotation")
Ry = np.transpose(rot_y(np.pi/3))
display(Ry)

Passive y axis rotation


array([[ 0.5      ,  0.       ,  0.8660254],
       [ 0.       ,  1.       ,  0.       ],
       [-0.8660254,  0.       ,  0.5      ]])

In [4]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap2.transforms import rot_x, rot_z

print("R = R_x(pi/3) @ R_z(pi/4)")
R = rot_x(np.pi/3) @ rot_z(np.pi/4)
display(R)

R = R_x(pi/3) @ R_z(pi/4)


array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.35355339,  0.35355339,  0.8660254 ],
       [ 0.61237244, -0.61237244,  0.5       ]])

In [8]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap2.transforms import rot_x, rot_y

R_a_to_b = rot_x(np.pi/6)
R_a_to_c = rot_y(np.pi/3)
R_d_to_c = rot_x(3*np.pi/4)

print("R_d^b = R_a_to_b*R_a_to_c^T*R_d_to_c")
R = R_a_to_b @ np.transpose(R_a_to_c) @ R_d_to_c
display(R)

R_d^b = R_a_to_b*R_a_to_c^T*R_d_to_c


array([[ 0.5       , -0.61237244, -0.61237244],
       [-0.4330127 , -0.78914913,  0.43559574],
       [-0.75      ,  0.04736717, -0.65973961]])

In [2]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap3.mav_dynamics_euler import derivatives_euler, DynamicStateEuler, IND_EULER
from mav_sim.chap3.mav_dynamics import ForceMoments

# Define forces and moments
fm = ForceMoments()
fm.fx = 1
fm.fy = 2
fm.fz = 3
fm.l = 4
fm.m = 5
fm.n = 6

# Define the state
st = DynamicStateEuler(np.zeros((12,1)))
st.north = 7
st.east = 8
st.down = 9
st.u = 10
st.v = 11
st.w = 12
st.phi = np.pi/3
st.theta = np.pi/6
st.psi = np.pi/9
st.p = 13
st.q = 14
st.r = 15

# Define the time derivative
x_dot = derivatives_euler(state = st.convert_to_numpy(), forces_moments= fm.to_array())
# print("Time derivative")
# display(x_dot)
print("d/dt psi = ", x_dot.item(IND_EULER.PSI))
print("d/dt r = ", x_dot.item(IND_EULER.R))




d/dt psi =  22.660254037844386
d/dt r =  -52.35197118263826
